export enum ErrorCode {
  ARGUMENT_VALIDATION_ERROR,
  INVALID_SIGNATURE,
  COLLECTION_NOT_FOUND,
  NFT_ITEM_NOT_FOUND,
  ORDER_NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  USER_NOT_FOUND,
  USER_NAME_OR_EMAIL_ALREADY_TAKEN,
  FILE_IS_NOT_ALLOWED,
  COULD_NOT_REMOVE_ORDER,
}

